---
- name: Create The SSH Public Key File
  copy: 
    src: ~/.ssh/id_rsa.pub
    dest: /root/.ssh/id_rsa.pub
    mode: 0644

- name: Create The SSH Private Key File
  copy:
    src: ~/.ssh/id_rsa
    dest: /root/.ssh/id_rsa
    mode: 0600

- name: Clone The git Repository
  git:
    repo: git@github.com:Klump-Inc/merchant-dashboard.git
    dest: /var/www/{{ domain }}
    version: release/develop
    accept_hostkey: yes
    clone: yes
    update: yes
