name: Lint Files and Run Test
"on": 
    push:
        branches:
          - main

env:
    VUE_APP_NODE_ENV: ${{ secrets.VUE_APP_NODE_ENV }}
    VUE_APP_API_URL:  ${{ secrets.VUE_APP_API_URL }}
    VUE_APP_CLIENT_ID: ${{ secrets.VUE_APP_CLIENT_ID }}
    VUE_APP_CLIENT_KEY: ${{ secrets.VUE_APP_CLIENT_KEY }}
    VUE_APP_CLIENT_SECRET: ${{ secrets.VUE_APP_CLIENT_SECRET }}
    VUE_APP_BUGSNAG_KEY: ${{ secrets.VUE_APP_BUGSNAG_KEY }}

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
