name: Lint Files and Run Test
"on": 
    push:
        branches:
          - main
    pull_request:
        branches:
          - main

env:
    VUE_APP_NODE_ENV: ${{ secrets.VUE_APP_NODE_ENV }}
    VUE_APP_API_URL:  ${{ secrets.VUE_APP_API_URL }}
    VUE_APP_CLIENT_ID: ${{ secrets.VUE_APP_CLIENT_ID }}
    VUE_APP_CLIENT_KEY: ${{ secrets.VUE_APP_CLIENT_KEY }}
    VUE_APP_CLIENT_SECRET: ${{ secrets.VUE_APP_CLIENT_SECRET }}
    VUE_APP_BUGSNAG_KEY: ${{ secrets.VUE_APP_BUGSNAG_KEY }}

jobs:
  lint-and-run-cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Eslinting
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
